### ISSUE TITLE
Share buttons on result page

### ISSUE THREAD

**Issue by Phisherman** [squarerootfury/distrochooser#32]
The share buttons on the result page could imply that somebody can share the results he/she made.

![result page](http://share.phishy.de/11861fb3489013d64632046821520ca4pflxYUZt.png)

I recommend to add some information text like *"Help distrochooser by sharing it with the world!"*

**Comment by squarerootfury** [comment]
The buttons are now replaced by a simple text box. The several social media services are to difficult to handle at this dialog.

![New](http://img.0fury.de/e514a5f66bbd1e08fea5e9cdf71b3ab8.png)
