### ISSUE TITLE
Questions!

### ISSUE THREAD

**Issue by squarerootfury** [squarerootfury/distrochooser#5]
Ask if he/she want to have several desktops installed and work some days with one and others with another one

Ask if he/she prefers to install each 6 months a new release or never have to  install a new release (Rolling Release)

Ask if you want to be bleeding edge or wait a little bit and be more stable

Ask if you want to use a lot of software out of the main repos or you are not so experimental 

Ask if you prefer a big repo as AUR for all the out of main software or a lot of little ones as PPAs﻿

**Comment by malteger** [comment]
:+1:

**Comment by squarerootfury** [comment]
Edit:

Question suggestion 1: Won't be included. 
Question suggestion 2: Included with the today's update
Question suggestion 3: Is included with suggestion 2

The other suggestions are not important enough for beginners (for them is the ldc made), so I will not include them.
